#!/bin/bash
# small utility to simplify the execution of daemon commands.

RED='\033[1;31m'
BLUE='\033[1;36m'
GREEN='\033[1;32m'
NC='\033[0m'

if [ -z $1 ]; then
        echo
        echo -e "${RED}ERROR: you must provide parameters.${NC}"
        echo -e "Syntax: ${BLUE}aem datadir command [options]${NC}"
        echo -e "ex.: ${GREEN}aem Atheneum2 masternode status${NC}"
        echo
        exit 1;
fi

if [ $2 == "start" ]; then
        /root/Atheneum/atheneumd -daemon -datadir=/root/.$1 -conf=/root/.$1/atheneum.conf
        exit 1;
fi

/root/Atheneum/atheneum-cli -datadir=/root/.$1 -conf=/root/.$1/atheneum.conf $2 $3 $4
